### ISSUE TITLE
Tutorial videos

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-legacy#1]
At the minimum one overview tutorial is needed. Here is the rest of the list:
- Possible workflows.
- What are different simulation recipes?  
- Image-based analysis
- Daylight factor, VSC
- Annual simulation
- Annual simulation + Dynamic blinds
- Results visualization
- ...

**Comment by AntoineDao** [comment]
Is this... resolved @mostaphaRoudsari ? Seems like we can probably close as it's not a code issue and pretty stale.

**Comment by mostaphaRoudsari** [comment]
Oh wow! 2014 - and there was a user who is now a ghost! https://github.com/ladybug-tools/honeybee-legacy/issues/1#event-88991885

We did released enough videos to be able to close this!
