### ISSUE TITLE
CSV file from OpenStudio's "Schedule:File"

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/honeybee-legacy#727]
Hi @chriswmackey ,

https://github.com/mostaphaRoudsari/honeybee/blob/71ab0eebb98c2482ce7cd45c984444ba347705e3/src/Honeybee_Export%20To%20OpenStudio.py#L4981-L5011

writeNonOSFeatures here removes ".csv" file extension in "Schedule:File" that generated from OpenStudio (this is new from 2.7)
![image](https://user-images.githubusercontent.com/9031066/62182153-8c43ed80-b323-11e9-8a6d-083cce50c71b.png)

![image](https://user-images.githubusercontent.com/9031066/62182311-273cc780-b324-11e9-8389-83d50a3cfd0f.png)

I know this was a workaround when OpenStudio didn't support "Schedule:File", but now this might cause issue if we are trying to use csv in OpenStudio.

Thanks,
Mingbo

**Comment by MingboPeng** [comment]
fixed in https://github.com/ladybug-tools/honeybee-legacy/pull/733

**Comment by chriswmackey** [comment]
Thanks for fixing this @MingboPeng . I'm so happy that OpenStudio now supports CSV schedules and we won't have to worry about this crazy workaround in honeybee[+]
