### ISSUE TITLE
Honeybee (in Dynamo) illumination result extrenly high

### ISSUE THREAD

**Issue by Koziu233** [ladybug-tools/honeybee-legacy#736]
Hi,

I'm new to honeybee and is attempting to run a point in time gride based daylight optimization within Dynamo (Revit) -Honeybee.

I'm aware that the `Collect Rooms and Spaces` node does not work well according to the current Autodesk policy. I chose to use the traditional way of making HoneybeeSurfaces.

However, I found the illumination result in lux being extremely high which seems unreasonable.
At some point close to the window, it even went up to over 30,000 lux. For example, the red point as shown in the figure.

![image](https://user-images.githubusercontent.com/45343457/69016548-3446fa80-0997-11ea-8e14-527758ed0f3a.png)

I'm not sure if I made any mistakes when setting up material properties.
The values I use for materials:

![image](https://user-images.githubusercontent.com/45343457/69016602-8e47c000-0997-11ea-9538-9df16df390de.png)

And I'm using weather data of London from energy plus:

![image](https://user-images.githubusercontent.com/45343457/69016611-a7507100-0997-11ea-8b46-a005d60d0809.png)

The script running seems to be successful without having problems, but the result seems to be strange.
It will be good if I can know where I made mistakes or in which part my knowledge is not enough.
Thank you very much.

My files: (currently using Dynamo 2.0.3)
[File_cc.zip](https://github.com/ladybug-tools/honeybee-legacy/files/3856322/File_cc.zip)

**Comment by chriswmackey** [comment]
This is not the correct place for this issue and it should be posted [here](https://github.com/ladybug-tools/honeybee-dynamo) instead.  Also, our Dynamo plugin is currently deprecated in the newer versions of Dynamo so you will likely have to go to an older version.
