### ISSUE TITLE
Error - Dump HB objects with shading controlled by Schedule

### ISSUE THREAD

**Issue by devngc** [ladybug-tools/honeybee-legacy#738]
https://discourse.ladybug.tools/t/error-dump-hb-objects-with-shading-controlled-by-schedule/8254?u=devang
I can look into this. I tested it and it does look like a bug.

**Comment by mostaphaRoudsari** [comment]
Not sure how much work it will take to address this issue. @devngc, it will be great if you can address this issue otherwise I'm tempted to consider this as not-fixed for the legacy and we will have an alternative solution in the [+] libraries. @chriswmackey what do you think?

**Comment by chriswmackey** [comment]
@devngc ,
It looks like it may be a quick fix if you want to go for it. I wouldn't spend more than an hour, though. Our system for serializing things into files is a lot more robust in the [+] plugins and we're hopefully just a month or two away from an official release.

**Comment by devngc** [comment]
Use [this](https://we.tl/t-1audLwsio0) file for testing

**Comment by devngc** [comment]
This is tested by Rafael [here](https://discourse.ladybug.tools/t/error-dump-hb-objects-with-shading-controlled-by-schedule/8254/4?u=devang)
