### ISSUE TITLE
Can`t run this microclimate analysis - Terminated by user

### ISSUE THREAD

**Issue by AnnaCPeres** [ladybug-tools/honeybee-legacy#748]
Hi everyone,
I am trying to run this Outdoor Microclimate analysis but for some reason end up getting the error that it was terminated by the user when it clearly wasnt. I`ve tried fixing it in every possible way, with no result. Could anyone please help me? 
GH file - https://drive.google.com/drive/folders/1OWKYFfhzUz27YyqIJwtenCIHkWG1bqRD?usp=sharing

**Comment by mostaphaRoudsari** [comment]
Hi @AnnaCPeres, you should post your questions to the forum: https://discourse.ladybug.tools
