### ISSUE TITLE
honeybee masses2zones error

### ISSUE THREAD

**Issue by smyliemeg** [ladybug-tools/honeybee-legacy#749]
![error index 1](https://user-images.githubusercontent.com/74729418/99704825-ce50ef80-2a90-11eb-84fe-6d819eef9bc3.png)

Hi all, Honeybee 0.0.65, component "Honeybee_Masses2Zones"
1. Solution exception:index out of range: 1

Any solutions? Have tried multiple geometries (closed breps), same issue.

**Comment by devngc** [comment]
Hi @smyliemeg,
I would recommend that you report this on https://discourse.ladybug.tools/
Somebody would have found a solution to this issue already.
