### ISSUE TITLE
Honeybee on a Mac - Installation and letting fly

### ISSUE THREAD

**Issue by aliceb99** [ladybug-tools/honeybee-legacy#750]
Hi there. I have downloaded Ladybug_0_0_69_Honeybee_0_0_66 on my MacBook. ladybug works fine, but honeybee will not work. I have tried reinstalling it and looked everywhere online, but I can't seem to work out what the problem is. All of the tools show up in my Grasshopper document under HB Legacy, but I can't actually use them. I think it is something to do with the installation somewhere as it tells me to 'let it fly', but when I drop the component to do so it comes up with an error message. I have attached a screenshot below.
<img width="1779" alt="Screenshot 2020-11-20 at 13 21 19" src="https://user-images.githubusercontent.com/74749434/99749818-4839b500-2b33-11eb-9100-18ad0a9977ea.png">
<img width="1789" alt="Screenshot 2020-11-20 at 13 21 51" src="https://user-images.githubusercontent.com/74749434/99749859-5b4c8500-2b33-11eb-891c-2eb72ebbff13.png">

**Comment by aliceb99** [comment]
I also tried installing Radiance 5.3 official release (2020-09-03) from this link https://github.com/LBNL-ETA/Radiance/releases, but couldn't get it to work

**Comment by devngc** [comment]
Hi @aliceb99,
The legacy plugins are not mac compatible.
Although not as developed as the legacy plugins but the [Ladybug 1.1.0](https://www.food4rhino.com/app/ladybug-tools) is mac compatible.

**Comment by mostaphaRoudsari** [comment]
@aliceb99, please post questions like this to the forum: https://discourse.ladybug.tools - thanks!
